### ISSUE TITLE
Why the distance beween neighboring residues is  1.0?

### ISSUE THREAD

**Issue by pyli0628** [prokia/drugVQA#2]
According to your distance equation, the distance between neighboring residues should be 0.5, calculated by:
![eq](https://user-images.githubusercontent.com/46222925/79195386-c2e57800-7e60-11ea-94c4-dd953e42eb38.GIF)
where both $d(r_i,r_j$  and d_0 are 3.8.
However, this distance in your data (contactMap) is 1.0.
Correct me if I am wrong!

**Comment by stepholi** [comment]
Sorry for the typo. This formart was the original version, where we updated the numerator from 1.0 to 2.0 in the current version.

**Comment by pyli0628** [comment]
Thank you very much for the prompt reply. But if the numerator was updated from 1.0 to 2.0, the distance between the residue of itself (e.g. r2 and r2) should be 2 (calculated by 2/(1+0)) instead of 1.  So why the distance between the residue of itself defined as 1?

**Comment by stepholi** [comment]
When calculating the distance map, there is no distance between the residue and itself. This "1" is set manually, and removing it can still achieve good results.

**Comment by LivC193** [comment]
Why did you change the numerator from 1 to 2 ? It holds no biological meaning. Did achieve better accuracy just by changing the numerator ?
